// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPtgXgJ37AeBF-SbySQaKfPtppET9HQO4',
    appId: '1:37030891226:web:7355145d9205db7bec9fe3',
    messagingSenderId: '37030891226',
    projectId: 'laptopharbour-b21fd',
    authDomain: 'laptopharbour-b21fd.firebaseapp.com',
    storageBucket: 'laptopharbour-b21fd.appspot.com',
    measurementId: 'G-L67Q2XX4PC',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPtgXgJ37AeBF-SbySQaKfPtppET9HQO4',
    appId: '1:37030891226:web:90540c78840b2001ec9fe3',
    messagingSenderId: '37030891226',
    projectId: 'laptopharbour-b21fd',
    authDomain: 'laptopharbour-b21fd.firebaseapp.com',
    storageBucket: 'laptopharbour-b21fd.appspot.com',
    measurementId: 'G-8FPTXL5YCE',
  );
}
